name: reserva_canchas
description: Aplicación para reservar canchas sintéticas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  provider: ^6.0.5
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/cancha11.jpg
    - assets/cancha2.jpg
    - assets/cancha3.jpg
    - assets/cancha4.jpg
    - assets/img1.png
    - assets/fondo.jpg
    - assets/fondo1.jpg
    - assets/fondo2.jpg
    - assets/colombia_flag.png
